services:
  postgres:
    container_name: postgres
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=in3omnia
      - POSTGRES_DB=movie-recommendations-api
    volumes:
      - postgres_data:/var/lib/postgresql/data
  user-api:
    build:
      context: .
      dockerfile: userMicroservice/Dockerfile
    container_name: user-api
    ports:
      - "9991:9991"
    depends_on:
      - postgres
    environment:
      - TZ=UTC
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/movie-recommendations-api

  movie-api:
    build:
      context: .
      dockerfile: movieMicroservice/Dockerfile
    container_name: movie-api
    ports:
      - "9992:9992"
    depends_on:
      - postgres
    environment:
      - TZ=UTC
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/movie-recommendations-api

  preference-api:
    build:
      context: .
      dockerfile: preferenceMicroservice/Dockerfile
    container_name: preference-api
    ports:
      - "9994:9994"
    depends_on:
      - postgres
    environment:
      - TZ=UTC
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/movie-recommendations-api

  rating-api:
    build:
      context: .
      dockerfile: ratingMicroservice/Dockerfile
    container_name: rating-api
    ports:
      - "9993:9993"
    depends_on:
      - postgres
    environment:
      - TZ=UTC
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/movie-recommendations-api

  recommendation-api:
    build:
      context: .
      dockerfile: recommendationMicroservice/Dockerfile
    container_name: recommendation-api
    ports:
      - "9995:9995"
    depends_on:
      - postgres
    environment:
      - TZ=UTC
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/movie-recommendations-api

volumes:
  postgres_data:
