image:
  repository: microservices-user-api
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 10
service:
  type: ClusterIP
  port: 9991

containerPort: 9991

env:
  datasource:
    url: jdbc:postgresql://user-api-postgresql:5432/user-api
    username: postgres
    password: postgres