apiVersion: v1
kind: Service
metadata:
  name: {{ include "movie-api.fullname" . }}

spec:
  type: {{ .Values.service.type }}

  selector:
    {{- include "movie-api.selectorLabels" . | nindent 4 }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}