apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-api
  template:
    metadata:
      labels:
        app: recommendation-api
    spec:
      containers:
        - name: recommendation-api
          image: microservices-recommendation-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9995
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/movie-recommendations-api
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: in3omnia
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9995
            initialDelaySeconds: 120
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9995
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5