apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: microservices-user-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9991
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/movie-recommendations-api
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: in3omnia
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: LOGGING_LEVEL_ROOT
              value: "INFO"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
              value: "WARN"
            - name: LOGGING_LEVEL_COM_NETFLIX_DISCOVERY
              value: "OFF"
            - name: LOGGING_LEVEL_COM_ZAXXER_HIKARI
              value: "WARN"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9991
            initialDelaySeconds: 120
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9991
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5