image:
  repository: microservices-user-api
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

service:
  type: ClusterIP
  port: 9991

containerPort: 9991

env:
  datasource:
    url: jdbc:postgresql://postgres-postgresql:5432/movie-recommendations-api
    username: postgres
    password: postgres   # ❗ краще потім через secret