server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/darryyna/microservices
          clone-on-start: true
          default-label: master
          search-paths: config-server/src/main/resources/config
          force-pull: true

logging:
  level:
    org.springframework.cloud.config: DEBUG