spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/darryyna/microservices
          clone-on-start: true
          default-label: master
          search-paths: config-server/src/main/resources/config
        prefix: application
      logging:
        level:
          org.springframework.cloud.config: DEBUG