server:
  port: 9995

spring:
  application:
    name: recommendation-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/movie-recommendations-api
    username: postgres
    password: in3omnia
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: localhost:9092

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger_ui

logging:
  level:
    org:
      springframework: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  consumer:
    group-id: movie-group
  topic:
    name: movie-topic

project:
  title: Recommendation Service API
