name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Compile
        run: mvn clean compile

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run tests (services only)
        run: mvn test -pl services/* -am

  sonar:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # важливо для Sonar

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build & Run JaCoCo
        run: mvn clean verify -pl services/* -am -Djacoco.skip=false

      - name: SonarCloud Scan (services only)
        run: mvn sonar:sonar \
          -pl services/* \
          -Dsonar.projectKey=darryyna_microservices \
          -Dsonar.organization=darryyna \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.java.coveragePlugin=jacoco \
          -Dsonar.coverage.jacoco.xmlReportPaths=services/*/target/site/jacoco/jacoco.xml